version: '3.8'

services:
  # api:
  #   build: .
  #   ports:
  #     - "${API_PORT:-4000}:4000"
  #   environment:
  #     - NODE_ENV=${NODE_ENV:-development}
  #     - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-saltybets}
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=${REDIS_PORT:-6379}
  #     - JWT_SECRET=${JWT_SECRET:-your-secret-key}
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - saltybets-network

  db:
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-saltybets}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saltybets-network

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - saltybets-network

volumes:
  postgres_data:
  redis_data:

networks:
  saltybets-network:
    driver: bridge 