import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ApolloProviderWrapper from './providers/ApolloProviderWrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout for the Next.js app. Only handles fonts and global styles.
 * ApolloProvider will be re-inserted by a provider component.
 * @param {object} props - The layout props.
 * @param {React.ReactNode} props.children - The page content.
 * @returns {JSX.Element} The rendered layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ApolloProviderWrapper>
          {/* ApolloProvider will be added by ApolloProviderWrapper */}
          {children}
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
